print('OS: ' .. love.system.getOS())
print('Screen: ' .. love.graphics.getWidth() .. 'x' .. love.graphics.getHeight())
print('RendererInfo:')
print(love.graphics.getRendererInfo())
print("LOVE:")
print(love.getVersion())
print('Press + to Quit')