#!/bin/bash

# Just for quickly copying over LovePotion for easy debugging.

HOST=$NINTENDO_IP
USER='anonymous'
PASSWD='anonymous'

echo Attempting to copy LovePotion over via ftp ...

ftp -n $HOST 5000 << EOT
binary
user $USER $PASSWD
cd /3ds/LovePotion
put LovePotion.3dsx
put LovePotion.smdh
put LovePotion.cia
bye
EOT

echo Done.