name: Nintendo 3DS

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                config: [release, debug]

        container:
            image: docker://devkitpro/devkitarm
            options: --cpus 2

        steps:
            - name: checkout
              uses: actions/checkout@v7

            - name: compile
              run: catnip -T 3DS ${{ matrix.config }}

            - id: commit
              run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: upload
              uses: actions/upload-artifact@v7
              with:
                  name: Nintendo 3DS-${{ steps.commit.outputs.short }} (${{ matrix.config }})
                  path: |
                      build/**/*.elf
                      build/**/*.3dsx
